src/GlobalStyle.ts
```
[ ] Bugfix
[x] Feature
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```
Sroll ugly
Scroll beautiful
```
[ ] Yes
[x] No
```
Scroll change to >
=> Update global style

src/web/pages/App/styles.ts
Change global style, by adding more things
```
[ ] Bugfix
[x] Feature
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```
No style for focus-visible, button and input
Styled for focus-visible, button and input
```
[ ] Yes
[x] No
```
=> Change global style

src/web/components/PageContainer/index.tsx, src/web/components/PageContainer/styles.ts, src/web/layouts/default/index.tsx, src/web/pages/App/index.tsx, src/web/pages/App/styles.ts, src/web/pages/Home/index.tsx, src/web/pages/Home/styles.ts
Adds page container
```
[ ] Bugfix
[x] Feature
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```
Repository without page container
Repository with page container
```
[ ] Yes
[x] No
```
=> Add page container

src/types/enums/layout.ts, src/web/components/PageContainer/index.tsx, src/web/layouts/default/index.tsx, src/web/layouts/default/styles.ts, src/web/layouts/wrapper.tsx
```
[ ] Bugfix
[x] Feature
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```
Repository with PageContainer
Repository withou PageContainer
```
[ ] Yes
[x] No
```
=> Remove PageContainer

src/assets/colors.ts
Fixed core colors
```
[ ] Hotfix
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
=> Fix core colors

.vscode/extensions.json, .vscode/settings.json
Added code default formatter
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> Add default formatter

src/web/pages/App/index.tsx, src/web/pages/App/styles.ts
Removed main from app
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> Remove main from app

src/web/layouts/wrapper.tsx, src/web/pages/App/index.tsx
Removed ...props from wrapper
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> Remove ...props from wrapper

jest.config.js, package.json, src/pages/_document.tsx, tsconfig.json, yarn.lock
Fix ESLint Errors
```
[ ] Hotfix
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> Fix ESLint Errors

.eslintrc.json, .vscode/settings.json, next.config.js, src/pages/_document.tsx, tsconfig.json
Fixed files with erros
```
[ ] Hotfix
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> Fix files with errors

.github/workflows/tests.yml, .vscode/settings.json
Added eslint test
```
[ ] Hotfix
[ ] Bugfix
[ ] Feature
[x] CI/CD related changes
```
```
[ ] Yes
[x] No
```
=> Add eslint test

.github/workflows/tests.yml
Added build test
```
[ ] Hotfix
[ ] Bugfix
[ ] Feature
[x] CI/CD related changes
```
```
[ ] Yes
[x] No
```
=> Add build test

package.json, yarn.lock
Removed lintstaged
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> Remove lintstaged

src/types/interfaces/layout.ts, src/web/pages/Home/index.tsx
Changed FcWithLayout to FCWithLayout
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> Change FcWithLayout to FCWithLayout

src/assets/translations/en-US/home.json, src/assets/translations/en-US/system.json, src/assets/translations/pt-BR/common.json, src/assets/translations/pt-BR/home.json, src/assets/translations/pt-BR/system.json, src/pages/_document.tsx, src/pages/index.tsx, src/types/interfaces/system.ts, src/web/components/HeadContent/index.tsx, src/web/pages/Home/index.tsx
Added multiple translations files
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> Add multiple translations files

src/types/interfaces/link.ts, src/web/components/Link/index.tsx
Added link component
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> Add link component

src/web/components/HeadTitle/index.tsx
Added HeadTitle component
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> Add HeadTitle component

src/assets/colors.ts, src/web/pages/MyApp/styles.ts
Fix colors
```
[ ] Hotfix
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> Fix colors

src/pages/_document.tsx, yarn.lock
Remove ESLint ignore no document import in page.
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
[ ] Other: ...
```
```
[ ] Yes
[x] No
```
=> Remove ESLint Ignore No Document Import In Page

src/web/pages/MyApp/styles.ts
Fix outline.
```
[ ] Hotfix
[x] Bugfix
[ ] Feature
[ ] Other: ...
```
```
[ ] Yes
[x] No
```
=> Fix Outline

src/web/pages/MyApp/styles.ts
Update media querys.
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
[ ] Other: ...
```
```
[ ] Yes
[x] No
```
=> Update Media Querys

.eslintignore, .github/workflows/tests.yml, .gitignore, SETUP.md, package.json, scripts/clone-core.sh, src/styles/colors.ts
Remove Core Integration
```
[ ] Hotfix
[ ] Bugfix
[x] Feature
[ ] Other: ...
```
```
[ ] Yes
[x] No
```
=> Remove Core Integration
